version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: szabi-webshop-be
    command: java -jar app.jar
    ports:
      - "8082:8082"
    restart: always
    volumes:
      - /home/dasza/app/sb-shop/volume:/src/src/data